# NumPy

<div class="admonition danger">
    <p class="admonition-title">DRAFT</p>
    <p style="padding-top: 1em">
        This page is a work in progress and is subject to change at any moment.
    </p>
</div>

Key resources:

-   [NumPy documentation](https://numpy.org/doc/stable)
-   [NumPy learn](https://numpy.org/learn/)

## Vanilla Python

Python, a versatile and powerful programming language, offers a range of high-level number objects and containers that form the foundation for various computational tasks.
Understanding these objects is crucial for effective programming.

High-level number objects, including integers and floating-point numbers, enable you to perform arithmetic operations with ease.

Containers are essential data structures in Python that facilitate the organization and manipulation of data. Two prominent containers are:

-   **Lists** provide costless insertion and appending operations, making them efficient for dynamic data storage. They are versatile and can store elements of different data types, allowing for flexibility in programming.
-   **Dictionaries** offer fast lookup capabilities by associating keys with values. This makes them ideal for scenarios where efficient data retrieval is crucial. Understanding how to leverage lists and dictionaries is fundamental for effective Python programming.

These are covered in [Python basics](../../python-basics/).

In [1]:
data_list = [0, 1, 2, 3, 4, 5]
print(data_list)

[0, 1, 2, 3, 4, 5]


## What is NumPy?

NumPy, short for Numerical Python, is a powerful extension package that enhances Python's capabilities for scientific computation.
Let's explore the key features and advantages that NumPy brings to the table.

## One-dimensional arrays

A one-dimensional array is a fundamental data structure in programming that represents a collection of elements stored in a linear sequence.
Each element in the array is identified by an index, starting from 0 for the first element.

In [2]:
import numpy as np

data_array = np.array([0, 1, 2, 3, 4, 5])
print(data_array)

[0 1 2 3 4 5]


In [3]:
list_added = [i + 2 for i in data_list]
print(f"List:  {list_added}")

array_added = data_array + 2
print(f"Array: {array_added}")

List:  [2, 3, 4, 5, 6, 7]
Array: [2 3 4 5 6 7]


In [4]:
list_sum = sum(data_list)
print(f"List:  {list_sum}")

array_sum = np.sum(data_array)
print(f"Array: {array_sum}")

List:  15
Array: 15


In [5]:
list_mean = sum(data_list) / len(data_list)
print(f"List:  {list_mean}")

array_mean = np.mean(data_array)
print(f"Array: {array_mean}")

List:  2.5
Array: 2.5


## Multi-dimensional arrays

NumPy introduces the concept of multi-dimensional arrays, providing a powerful and efficient data structure for numerical computations.
These arrays allow for seamless handling of matrices and other multi-dimensional data, a crucial feature in scientific computing.

In [6]:
data_2d_list = [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]
print("List")
print(data_2d_list)

data_2d_array = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]])
print("Array")
print(data_2d_array)

List
[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]
Array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [7]:
list_2d_added = []
for row in data_2d_list:
    list_2d_added.append([])
    for value in row:
        list_2d_added[-1].append(value + 2)
print("List")
print(list_2d_added)

array_2d_added = data_2d_array + 2
print("Array")
print(array_2d_added)

List
[[2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13]]
Array
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]]


In [8]:
list_2d_sum = 0
for row in data_2d_list:
    for element in row:
        list_2d_sum += element
print(f"List:  {list_2d_sum}")

array_2d_sum = np.sum(data_2d_array)
print(f"Array: {array_2d_sum}")

List:  66
Array: 66


In [9]:
list_2d_sum = 0
list_2d_n = 0
for row in data_2d_list:
    for item in row:
        list_2d_sum += item
        list_2d_n += 1
list_2d_mean = list_2d_sum / list_2d_n
print(f"List:  {list_2d_mean}")

array_2d_mean = np.mean(data_2d_array)
print(f"Array: {array_2d_mean}")

List:  5.5
Array: 5.5


## Creating arrays

[Documentation](https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation)

### `np.linspace`

Creates an array with evenly spaced values over a specified range.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [10]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


### `np.arange`

Creates an array with regularly spaced values within a given interval.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

In [11]:
arange_array = np.arange(10)
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


### `np.zeros`

Creates an array filled with zeros.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [12]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


### `np.full`

Return a new array of given shape and type, filled with fill_value.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.full.html)

In [13]:
full_array = np.full((2, 2), np.nan)
print(full_array)

[[nan nan]
 [nan nan]]


## Indexing and slicing

In Python, the colon `:` is used for slicing in sequences, such as strings, lists, and NumPy arrays.
The syntax for slicing is generally `start:stop:step`.
Here's an explanation of each part:

-   `start`: The index at which the slice begins (inclusive). If omitted, it defaults to the beginning of the sequence.
-   `stop`: The index at which the slice ends (exclusive). If omitted, it defaults to the end of the sequence.
-   `step`: The step size or the number of indices between each slice. If omitted, it defaults to 1.

[Documentation](https://numpy.org/doc/stable/user/basics.indexing.html)

In [14]:
array = np.array(
    [
        [0, 1, 2, 3, 4, 5],
        [10, 11, 12, 13, 14, 15],
        [20, 21, 22, 23, 24, 25],
        [30, 31, 32, 33, 34, 35],
        [40, 41, 42, 43, 44, 45],
        [50, 51, 52, 53, 54, 55],
    ]
)
print(array)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [15]:
array[0]

array([0, 1, 2, 3, 4, 5])

In [16]:
array[0, 3:5]

array([3, 4])

In [17]:
array[4:, 4:]

array([[44, 45],
       [54, 55]])

In [18]:
array[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [19]:
array[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

## Acknowledgements

Some material here was adapted with permission from the following sources:

-   [Scientific Python Lectures](https://github.com/scipy-lectures/scientific-python-lectures)